---
title: "Classes and methods for structural variant analyses"
author: "Robert Scharpf"
date: \today
output: BiocStyle::pdf_document
bibliography:
vignette: >
  %\VignetteIndexEntry{Classes and methods for structural variant analyses}
  %\VignetteEngine{knitr::rmarkdown}
  %\usepackage[utf8]{inputenc} 
---


```{r lib}
library(svclasses)
```


```{r overview-svanalyses}
library(grid)
myGrob <- function(x, r=unit(0.25, "inches")){
  tg <- textGrob(x)
  cg <- circleGrob(r=r)
  boxedText <- gTree(children=gList(tg, cg))
}
plotGrob <- function(g, x, y, fill="gray80", color="steelblue"){
  grid.draw(editGrob(g, vp=viewport(x, y), gp=gpar(fill=fill)))
  grid.draw(editGrob(g, vp=viewport(x, y),
                     gp=gpar(fill="transparent", color=color)))
}
grobRD <- myGrob("RD")
grobPR <- myGrob("PR")
grobSR <- myGrob("SR")
grobD <- myGrob("D")
grobA <- myGrob("A")
grobI <- myGrob("I")
grobT <- myGrob("T")

h <- unit(0.3, "inches")
e <- unit(0.05, "inches")
d <- unit(0.025, "inches")
ar <- arrow(ends="last", length=unit(0.075, "inches"), type="closed")

##pdf("~/Labs/Scharpf/Cristianoetal/model/graph.pdf", width=8, height=6)
grid.newpage()
x <- rep(0.2, 3)
y <- c(0.8, 0.5, 0.2)
plotGrob(grobRD, x=x[1], y=y[1])
plotGrob(grobPR, x=x[1], y=y[2])
plotGrob(grobSR, x=x[1], y=y[3])

x2 <- 0.5
y2 <- seq(0.9, 0.1, by=-0.25)
plotGrob(grobD, x=x2[1], y=y2[1], fill="lightblue")
plotGrob(grobA, x=x2[1], y=y2[2], fill="salmon")
plotGrob(grobI, x=x2[1], y=y2[3], fill="orange")
plotGrob(grobT, x=x2[1], y=y2[4], fill="beige")

# connections
## RD -> D
grid.move.to(unit(x[1], "npc") + h, unit(y[1], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[1], "npc"), arrow=ar,
             gp=gpar(fill="black"))

## PR -> D
grid.move.to(unit(x[1], "npc") + h, unit(y[2], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[1], "npc") - 1/3*h, arrow=ar,
             gp=gpar(fill="black"))

## RD -> A
grid.move.to(unit(x[1], "npc") + h, unit(y[1], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[2], "npc") + 1/5*h, arrow=ar,
             gp=gpar(fill="black"))

## PR -> A
grid.move.to(unit(x[1], "npc") + h, unit(y[2], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[2], "npc") - 1/5*h, arrow=ar,
             gp=gpar(fill="black"))

## PR -> I
grid.move.to(unit(x[1], "npc") + h, unit(y[2], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[3], "npc") + 1/5*h, arrow=ar,
             gp=gpar(fill="black"))

## PR -> T
grid.move.to(unit(x[o1], "npc") + h, unit(y[2], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[4], "npc") + 1/5*h, arrow=ar,
             gp=gpar(fill="black"))

## SR -> T
grid.move.to(unit(x[1], "npc") + h, unit(y[3], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[4], "npc") - 1/5*h, arrow=ar,
             gp=gpar(fill="black"))

## SR -> I
grid.move.to(unit(x[1], "npc") + h, unit(y[3], "npc"))
grid.line.to(unit(x2[1], "npc") - h, unit(y2[3], "npc") - 1/5*h, arrow=ar,
             gp=gpar(fill="black"))

##
## Read depth icon
##
rd <- rnorm(10, 0, 0.15)
rd[5:7] <- rnorm(3, -1, 0.15)
df <- data.frame(y=rd, x=seq_along(rd))
df.segs <- data.frame(x=c(0, 5, 8), xend=c(4, 7, 10),
                      y=c(0, -1, 0))
library(ggplot2)
rd.fig <- ggplot(df, aes(x, y)) + geom_point(size=5, color="gray50") + theme_void() +
  ylim(c(-2, 1)) +
  geom_segment(data=df.segs, aes(x=x, xend=xend, y=y, yend=y),
               size=3)

##
## paired read icon
##
df <- data.frame(y=rd, x=seq_along(rd))
df.segs <- data.frame(x=c(0, 5, 8), xend=c(4, 7, 10),
                      y=c(0, -1, 0))
library(ggplot2)
rd.fig <- ggplot(df, aes(x, y)) + geom_point(size=5, color="gray50") + theme_void() +
  ylim(c(-2, 1)) +
  geom_segment(data=df.segs, aes(x=x, xend=xend, y=y, yend=y),
               size=3)
##
## Add circos figure to right
##
```

```{r}


```

