context("AlignmentViews")
test_that("AlignmentViews", {
  av <-  AlignmentViews2()
  expect_true(validObject(av))
  expect_identical(rdsId(av), character())
  
  library(Rsamtools)
  require(TestBams)
  extdata <- system.file("extdata", package="TestBams")
  bam.file <- list.files(extdata, pattern="\\.bam$", full.name=TRUE)
  bv <- BamViews(bam.file)
  dp <- tempfile()
  aviews <- AlignmentViews2(bv, dp)
  expect_error(validObject(aviews))
  files <- replicate(2, tempfile())
  aviews <- AlignmentViews2(bv, files)
  expect_identical(length(improperPaths(aviews)),
                   ncol(bv))
  expect_true(validObject(aviews[, 1]))
})
